minio:
  endpoint:  http://192.168.0.2:900
  public-endpoint: https://minio.eeccc.cc
  access-key: admin
  secret-key: 2932349894

spring:
  datasource:
    url: jdbc:mysql://192.168.0.2:3306/minio?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver