minio:
  endpoint: http://192.168.0.6:9000
  public-endpoint: http://192.168.0.6:9000
  access-key: admin
  secret-key: 2932349894

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minio?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver